In [1]:
import torch

t1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float32)
t2 = torch.ones((2, 2))
t3 = torch.randn(2, 2)

print("t1:", t1)
print("t2:", t2)
print("t3:", t3)

add_res = t1 + t2
mul_res = t1 * 5
sub_res = t1 - t3
idx_res = t1[:, 1]
reshaped = t1.view(4)

print("Addition Result (t1 + t2):")
print(add_res)
print("Multiplication Result (t1 * 5):")
print(mul_res)
print("Subtraction Result (t1 - t3):")
print(sub_res)
print("Indexing Result (t1[:, 1]):", idx_res)
print("Reshaped Tensor (t1.view(4)):", reshaped)

x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 5*x
y.backward()
grad_val = x.grad

print("Gradient (x.grad):", grad_val)

t1: tensor([[1., 2.],
        [3., 4.]])
t2: tensor([[1., 1.],
        [1., 1.]])
t3: tensor([[-0.2422,  0.2289],
        [-0.0603,  1.0391]])
Addition Result (t1 + t2):
tensor([[2., 3.],
        [4., 5.]])
Multiplication Result (t1 * 5):
tensor([[ 5., 10.],
        [15., 20.]])
Subtraction Result (t1 - t3):
tensor([[1.2422, 1.7711],
        [3.0603, 2.9609]])
Indexing Result (t1[:, 1]): tensor([2., 4.])
Reshaped Tensor (t1.view(4)): tensor([1., 2., 3., 4.])
Gradient (x.grad): tensor([9.])


In [13]:
import tensorflow as tf

mat_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
mat_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print("Matrix A:")
print(mat_a.numpy())
print("Matrix B:")
print(mat_b.numpy())

add_tf = tf.add(mat_a, mat_b)
matmul_tf = tf.matmul(mat_a, mat_b)
transpose_tf = tf.transpose(mat_a)
det_tf = tf.linalg.det(mat_a)
inv_tf = tf.linalg.inv(mat_a)
eig_vals, eig_vecs = tf.linalg.eigh(mat_a)

print("Addition (mat_a + mat_b):")
print(add_tf.numpy())
print("Matrix Multiplication (mat_a @ mat_b):")
print(matmul_tf.numpy())
print("Transpose of mat_a:")
print(transpose_tf.numpy())
print("Determinant of mat_a:", det_tf.numpy())
print("Inverse of mat_a:")
print(inv_tf.numpy())
print("Eigenvalues of mat_a:", eig_vals.numpy())
print("Eigenvectors of mat_a:")
print(eig_vecs.numpy())

Matrix A:
[[1. 2.]
 [3. 4.]]
Matrix B:
[[5. 6.]
 [7. 8.]]
Addition (mat_a + mat_b):
[[ 6.  8.]
 [10. 12.]]
Matrix Multiplication (mat_a @ mat_b):
[[19. 22.]
 [43. 50.]]
Transpose of mat_a:
[[1. 3.]
 [2. 4.]]
Determinant of mat_a: -2.0
Inverse of mat_a:
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]
Eigenvalues of mat_a: [-0.8541021  5.854102 ]
Eigenvectors of mat_a:
[[-0.85065085 -0.5257311 ]
 [ 0.5257311  -0.85065085]]


In [9]:
import numpy as np

def perceptron(inputs, weights, bias):
    activation = np.dot(inputs, weights) + bias
    return 1 if activation >= 0 else 0

def solve_gate(gate_type):
    inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
    if gate_type == "AND":
        w, b = np.array([1, 1]), -1.5
    elif gate_type == "OR":
        w, b = np.array([1, 1]), -0.5
    else:
        return "Unsupported gate type"

    return [perceptron(i, w, b) for i in inputs]

and_results = solve_gate("AND")
or_results = solve_gate("OR")

print("AND Gate Results:", and_results)
print("OR Gate Results:", or_results)

AND Gate Results: [0, 0, 0, 1]
OR Gate Results: [0, 1, 1, 1]


In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float32)
Y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

model_xor = nn.Sequential(
    nn.Linear(2, 4),
    nn.Sigmoid(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.Adam(model_xor.parameters(), lr=0.1)

for epoch in range(500):
    optimizer.zero_grad()
    outputs = model_xor(X)
    loss = criterion(outputs, Y)
    loss.backward()
    optimizer.step()

print("Final Loss after training:", loss.item())
outputs_final = model_xor(X)
print("Final predictions on input X:")
print(outputs_final.detach().numpy())

Final Loss after training: 0.0016351693775504827
Final predictions on input X:
[[1.1125613e-04]
 [9.9952531e-01]
 [9.9752003e-01]
 [3.4452819e-03]]


In [11]:
import torch
import torch.nn as nn

class RegressionNN(nn.Module):
    def __init__(self):
        super(RegressionNN, self).__init__()
        self.hidden = nn.Linear(2, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.sigmoid(self.hidden(x))
        x = self.output(x)
        return x

model_reg = RegressionNN()
dummy_input = torch.tensor([[0.5, 0.8]], dtype=torch.float32)
prediction = model_reg(dummy_input)

print("Model prediction for dummy input:", prediction.item())

Model prediction for dummy input: -0.017223209142684937
